import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/config/styles/globals.css';
import { QueryProvider } from "./providers/query-provider";
import HeaderComponent from "../widgets/header/header-component";
import { Toaster } from "sonner";

  const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-6xl mx-auto flex flex-col items-center justify-center`}>
        <QueryProvider>
          <HeaderComponent />
          <Toaster />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
